GET http://localhost:8080
Accept: application/json


###
POST http://localhost:8080/add-product
Content-Type: application/json

{
  "id": 1,
  "title": "Mobile",
  "description": "Mobile"
}

###
GET http://localhost:8080/products
Accept: application/json

###
GET http://localhost:8080/not-found
Accept: application/json

###

